# The minimal docker compose file which should be used for backend development
# Run it with:
# docker compose -f compose.dev.yaml up (-d for detached mode)

# Contains only the backend infrastructure services:
# - Caddy (proxy), possibly useful.
# - ActiveMQ (message broker), to be replaced with RabbitMQ
# - Bank Service PostgreSQL database
# - User Service PostgreSQL database


services:
  proxy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - user-net
      - banking-net
      - notification-net
      - proxy-net
      - broker-net
    # Required on linux for host.docker.internal to be accessible
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - user-service
      - banking-service
  dev-message-broker:
    image: 'apache/activemq-classic:latest'
    ports:
      - '61616:61616'
    volumes:
      - 'dev_activemq_data:/opt/activemq/data'
  dev-banking-db:
    image: 'postgres:17-alpine'
    ports:
        - '5433:5432'
    environment:
      POSTGRES_USER: banking_service_user
      POSTGRES_PASSWORD: banking_service_password
      POSTGRES_DB: banking_db
    volumes:
      - 'dev_banking_db_data:/var/lib/postgresql/data/'
  dev-user-db:
    image: 'postgres:17-alpine'
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: user_service_user
      POSTGRES_PASSWORD: user_service_password
      POSTGRES_DB: user_service_db
    volumes:
      - 'dev_user_db_data:/var/lib/postgresql/data/'
volumes:
  dev_activemq_data: null
  dev_banking_db_data: null
  dev_user_db_data: null