spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: user-service
            uri:  ${USER_SERVICE_URI:http://localhost:8081}
            predicates:
              - Path=/api/user/**
            filters:
              - RewritePath=/api/user/(?<segment>.*), /$\{segment}
              - TokenRelay=
          - id: banking-service
            uri: ${BANKING_SERVICE_URI:http://localhost:8082}
            predicates:
              - Path=/api/banking/**
            filters:
              - RewritePath=/api/banking/(?<segment>.*), /$\{segment}
              - TokenRelay=
          - id: trading-service
            uri: ${TRADING_SERVICE_URI:http://localhost:3000}
            predicates:
              - Path=/api/trading/**
            filters:
              - RewritePath=/api/trading/(?<segment>.*), /$\{segment}
              - TokenRelay=
          - id: support-service
            uri: ${SUPPORT_SERVICE_URI:http://localhost:8000}
            predicates:
              - Path=/api/support/**
            filters:
              - RewritePath=/api/support/(?<segment>.*), /$\{segment}
              - TokenRelay=
  security:
    oauth2:
      client:
        provider:
          idp:
            issuer-uri: ${IDP_ISSUER_URI:https://idp.localhost}
        registration:
          idp:
            provider: idp
            client-id: ${IDP_CLIENT_ID:gateway-client}
            client-secret: ${IDP_CLIENT_SECRET:secrets}
            scope: openid, profile, email
            authorization-grant-type: authorization_code
            redirect-uri: ${IDP_REDIRECT_URI:https://localhost/api/login/oauth2/code/idp}
            client-name: idp
  output:
    ansi:
      enabled: always
  session:
    timeout: 180m
logging:
  level:
    org.springframework.security: trace
server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: sid
        same-site: lax